-- Database Exploration

-- Explore All objects in the Database
SELECT * FROM INFORMATION_SCHEMA.TABLES

-- Explore All Columns in the Database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'dim_customers'


-- Dimension Exploration
-- Identifying the unique values or categories in each dimension
-- Recognizing how data might be grouped or segmented, which is useful for later analysis

SELECT DISTINCT country FROM dim_customers

-- Explore all categories "The Major Divisions"
SELECT DISTINCT category,subcategory,product_name FROM dim_products
ORDER BY 1,2,3


-- Data Exploration
-- Identify the earliest and latest dates(boundaries)
-- Understand the scope of data and the timespan

-- Find the date of the first and last order
-- How many years of sales are available
SELECT MIN(order_date)first_order_date, MAX(order_date)last_order_date,
DATEDIFF(year, MIN(order_date), MAX(order_date)) AS order_range_years FROM fact_sales

-- Find the youngest and oldest customer
SELECT MIN(birthdate)youngest, DATEDIFF(year,MIN(birthdate),GETDATE())youngest_age,
	   MAX(birthdate)oldest, DATEDIFF(year,MAX(birthdate),GETDATE())oldest_age
FROM dim_customers


-- Measures Exploration
-- Calculate the key metric of the business(Big Numbers)
-- Highest level of Aggregation | Lowest level of Details

-- Find the Total Sales
SELECT SUM(sales_amount)total_sales FROM fact_sales

-- Find how many items are sold
SELECT SUM(quantity)items_sold FROM fact_sales

-- Find the average selling price
SELECT AVG(price)avg_price FROM fact_sales

-- Find the total number of Orders
SELECT COUNT(order_number)total_orders FROM fact_sales
SELECT COUNT(DISTINCT order_number)total_orders FROM fact_sales

-- Find the total number of Products
SELECT COUNT(product_key)total_products FROM dim_products
SELECT COUNT(DISTINCT product_key)total_products FROM dim_products

-- Find the total number of Customers
SELECT COUNT(customer_key)total_customers FROM dim_customers
SELECT COUNT(DISTINCT customer_key)total_customers FROM dim_customers

-- Find the total umber of Customers that has place and Order
SELECT COUNT(DISTINCT customer_key)total_customers_orders FROM fact_sales

-- Generate a Report that shows all key metrics of the business
SELECT 'Total Sales' AS measure_name, SUM(sales_amount)measure_value FROM fact_sales
UNION ALL
SELECT 'Total Quantity', SUM(quantity) FROM fact_sales
UNION ALL
SELECT 'Average Price', AVG(price) FROM fact_sales
UNION ALL
SELECT 'Total Nr. Orders', COUNT(DISTINCT order_number) FROM fact_sales
UNION ALL
SELECT 'Total Nr. Products', COUNT(product_key) FROM dim_products
UNION ALL 
SELECT 'Total Nr. Customers', COUNT(customer_key) FROM dim_customers 


-- Magnitude Analysis
-- Compare the measure values by category
-- It helps Understand the importance of different categories

-- Find the total customers by countries
SELECT country, COUNT(customer_key) AS total_customers FROM dim_customers
GROUP BY country ORDER BY total_customers DESC

-- Find total customers by gender
SELECT gender, COUNT(customer_key) AS total_customers FROM dim_customers
GROUP BY gender ORDER BY total_customers

-- Find total products by category
SELECT category, COUNT(product_key)total_products FROM dim_products
GROUP BY category, ORDER BY total_products DESC

-- What is the average cost in each category?
SELECT category, AVG(cost)avg_costs FROM dim_products
GROUP BY category ORDER BY avg_costs DESC

-- What is the total revenue generated for each category
SELECT p.category, SUM(f.sales_amount)total_revenue FROM fact_sales f
LEFT JOIN dim_products p ON p.product_id = f.product_key
GROUP BY p.category ORDER BY total_revenue DESC

-- Find total revenue generated by each customer
SELECT c.customer_key, c.first_name, c.last_name, SUM(f.sales_amount)total_revenue FROM fact_sales f
LEFT JOIN dim_customers c ON c.customer_key = f.customer_key
GROUP BY c.customer_key,c.first_name,c.last_name ORDER BY total_revenue DESC

-- What is the distribution of sold items across countries?
SELECT c.country, SUM(f.quantity)total_items_sold FROM fact_sales f
LEFT JOIN dim_customers c ON c.customer_key = f.customer_key
GROUP BY c.country ORDER BY total_items_sold DESC


-- Ranking analysis
-- Order the values of dimensions by measure
-- Top N performers | Bottom N performers
SELECT TOP 5 p.product_name, SUM(f.sales_amount)total_revenue FROM fact_sales f
LEFT JOIN dim_products p ON p.product_id = f.product_key
GROUP BY p.product_name ORDER BY total_revenue DESC

SELECT * FROM (
	SELECT p.product_name, SUM(f.sales_amount)total_revenue,
	ROW_NUMBER()OVER(ORDER BY SUM(f.sales_amount)DESC) AS rank_products
	FROM fact_sales f
	LEFT JOIN dim_products p ON p.product_key = f.product_key
	GROUP BY p.product_name
)t WHERE rank_products <= 5

-- What are the 5 worst performing products in term of sales?
SELECT TOP 5 p.product_name, SUM(f.sales_amount)total_revenue FROM fact_sales f
LEFT JOIN dim_products p ON p.product_id = f.product_key
GROUP BY p.product_name ORDER BY total_revenue

-- Find the top 10 customers who have generated the highest revenue
SELECT TOP 10 c.customer_key, c.first_name, c.last_name, SUM(f.sales_amount)total_revenue FROM fact_sales f
LEFT JOIN dim_customers c ON c.customer_key = f.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name ORDER BY total_revenue DESC

-- Find the 3 customers with the fewest orders placed
SELECT TOP 3 c.customer_key, c.first_name, c.last_name, COUNT(DISTINCT order_number)total_orders FROM fact_sales f
LEFT JOIN dim_customers c ON c.customer_key = f.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name ORDER BY total_orders
